# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: SeamOS Blog
email: yonnyquiceno@gmail.com
description: SeamOS es una plataforma ciudadana y tecnol√≥gica que busca utilizar las TICs para actualizar la democracia.
baseurl: "/blog_seamos" # the subpath of your site, e.g. /blog
url: "https://yonnyquiceno.github.io/blog_seamos/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: seamos
github_username:  yonnyquiceno
excerpt_separator: <!-- more -->
lang: es
locale: es_CO
image: "/assets/images/LogoSeamos.png"

# google_analytics: UA-18132057-9

# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-feed
  - jekyll-redirect-from

sass:
  sass_dir: ./_sass

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - README.md
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
